apiVersion: apps/v1
kind: Deployment
metadata:
  name: microserviceone
spec:
  replicas: 3
  selector:
    matchLabels:
      app: microserviceone
      version: v1.0
  template:
    metadata:
      labels:
        app: microserviceone
        version: v1.0
    spec:
      containers:
        - name: microserviceone
          image: miranotest.azurecr.io/microserviceone:latest
          ports:
            - containerPort: 80